"""init3

Revision ID: 588c980ea673
Revises: 1547d1dc8e62
Create Date: 2024-06-27 01:02:43.878228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588c980ea673'
down_revision: Union[str, None] = '1547d1dc8e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('snippet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'snippets', ['snippet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'snippet_id')
    # ### end Alembic commands ###
