"""init4

Revision ID: 78ea04cc30bd
Revises: 588c980ea673
Create Date: 2024-06-27 01:53:53.278934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ea04cc30bd'
down_revision: Union[str, None] = '588c980ea673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('salaries_vacancy_id_key', 'salaries', type_='unique')
    op.drop_constraint('salaries_vacancy_id_fkey', 'salaries', type_='foreignkey')
    op.drop_column('salaries', 'vacancy_id')
    op.drop_constraint('snippets_vacancy_id_key', 'snippets', type_='unique')
    op.drop_constraint('snippets_vacancy_id_fkey', 'snippets', type_='foreignkey')
    op.drop_column('snippets', 'vacancy_id')
    op.add_column('vacancies', sa.Column('employer_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'employers', ['employer_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'employer_name')
    op.add_column('snippets', sa.Column('vacancy_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('snippets_vacancy_id_fkey', 'snippets', 'vacancies', ['vacancy_id'], ['id'])
    op.create_unique_constraint('snippets_vacancy_id_key', 'snippets', ['vacancy_id'])
    op.add_column('salaries', sa.Column('vacancy_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('salaries_vacancy_id_fkey', 'salaries', 'vacancies', ['vacancy_id'], ['id'])
    op.create_unique_constraint('salaries_vacancy_id_key', 'salaries', ['vacancy_id'])
    # ### end Alembic commands ###
