"""Create tables

Revision ID: 2328d174a206
Revises: 
Create Date: 2024-06-26 14:43:43.087322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2328d174a206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('alternate_url', sa.String(), nullable=False),
    sa.Column('logo_urls', sa.JSON(), nullable=False),
    sa.Column('vacancies_url', sa.String(), nullable=False),
    sa.Column('accredited_it_employer', sa.Boolean(), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('has_test', sa.Boolean(), nullable=False),
    sa.Column('response_letter_required', sa.Boolean(), nullable=False),
    sa.Column('area_id', sa.String(), nullable=False),
    sa.Column('salary', sa.JSON(), nullable=True),
    sa.Column('type', sa.JSON(), nullable=False),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('response_url', sa.String(), nullable=True),
    sa.Column('sort_point_distance', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('apply_alternate_url', sa.String(), nullable=False),
    sa.Column('show_logo_in_search', sa.Boolean(), nullable=True),
    sa.Column('insider_interview', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('alternate_url', sa.String(), nullable=False),
    sa.Column('relations', sa.JSON(), nullable=False),
    sa.Column('employer_id', sa.String(), nullable=False),
    sa.Column('snippet', sa.JSON(), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('working_time_intervals', sa.JSON(), nullable=False),
    sa.Column('working_time_modes', sa.JSON(), nullable=False),
    sa.Column('accept_temporary', sa.Boolean(), nullable=False),
    sa.Column('professional_roles', sa.JSON(), nullable=False),
    sa.Column('accept_incomplete_resumes', sa.Boolean(), nullable=False),
    sa.Column('experience', sa.JSON(), nullable=False),
    sa.Column('employment', sa.JSON(), nullable=False),
    sa.Column('adv_response_url', sa.String(), nullable=True),
    sa.Column('is_adv_vacancy', sa.Boolean(), nullable=False),
    sa.Column('adv_context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    op.drop_table('user')
    op.drop_table('employers')
    op.drop_table('areas')
    # ### end Alembic commands ###
